[package]

name = "grpc"
version = "0.0.1"

[dependencies]
solicit     = { git = "http://github.com/mlalic/solicit.git" }
protobuf    = { path = "../rust-protobuf" }
#               git = "http://github.com/stepancheg/rust-protobuf"
futures     = { git = "https://github.com/alexcrichton/futures-rs" }
futures-mio = { git = "https://github.com/alexcrichton/futures-rs" }

[[bin]]

name = "protoc-gen-rust-grpc"
test = false

[[bin]]

name = "temp-server"
test = false

[workspace]
members = [
    "grpc-examples",
]
